/**
 * Daily QT reading-plan algorithm — ported from the app's
 * src/lib/dailyPlan.ts (+ computus.ts + data/verseCounts.ts +
 * data/christmasReadings.ts) so the worker's cron trigger can
 * independently compute "today's reading" and pre-warm the
 * /qt-reflection cache before anyone opens the app.  Keep this in
 * sync by hand if the app's algorithm ever changes — there's no
 * shared package between the two repos.
 *
 * bookIdx is 0-indexed, matching this file's own BOOK_CHAPTERS /
 * VERSE_COUNTS order — the same standard 66-book Protestant order as
 * index.js's BOOK_NAMES_EN/BOOK_NAMES_KO/BOOK_CHAPTERS.
 */

const BOOK_CHAPTERS = [50,40,27,36,34,24,21,4,31,24,22,25,29,36,10,13,10,42,150,31,12,8,66,52,5,48,12,14,3,9,1,4,7,3,3,3,2,14,4,28,16,24,21,28,16,16,13,6,6,4,4,5,3,6,4,3,1,13,5,5,3,5,1,1,1,22];

// bookIdx -> [chapter-1] -> verse count.  Copied verbatim from
// src/data/verseCounts.ts (generated by scripts/fetchVerseCounts.ts).
const VERSE_COUNTS = [[31,25,24,26,32,22,24,22,29,32,32,20,18,24,21,16,27,33,38,18,34,24,20,67,34,35,46,22,35,43,55,32,20,31,29,43,36,30,23,23,57,38,34,34,28,34,31,22,33,26],[22,25,22,31,23,30,25,32,35,29,10,51,22,31,27,36,16,27,25,26,36,31,33,18,40,37,21,43,46,38,18,35,23,35,35,38,29,31,43,38],[17,16,17,35,19,30,38,36,24,20,47,8,59,57,33,34,16,30,37,27,24,33,44,23,55,46,34],[54,34,51,49,31,27,89,26,23,36,35,16,33,45,41,50,13,32,22,29,35,41,30,25,18,65,23,31,40,16,54,42,56,29,34,13],[46,37,29,49,33,24,26,20,29,22,32,32,18,29,22,22,20,22,21,20,23,30,25,22,19,19,26,68,29,19,30,52,29,12],[18,24,17,24,15,27,26,35,27,43,23,24,33,15,63,10,18,28,51,9,45,34,16,33],[36,23,31,24,31,40,25,35,57,18,40,15,25,20,20,31,13,31,30,48,25],[22,23,18,22],[28,36,21,22,12,21,17,22,27,27,15,25,23,52,35,23,58,30,24,42,15,23,29,22,44,25,12,25,11,31,13],[27,32,39,12,25,23,29,18,13,19,27,31,39,33,37,23,29,33,43,26,22,51,39,25],[53,46,28,34,18,38,51,66,28,29,43,33,34,31,34,34,24,46,21,43,29,53],[18,25,27,44,27,33,20,29,37,36,21,21,25,29,38,20,41,37,37,21,26,20,37,20,30],[54,55,24,43,26,81,40,40,44,14,47,40,14,17,29,42,27,17,19,8,30,19,32,31,31,32,34,21,30],[17,18,17,22,14,42,22,18,31,19,23,16,22,15,19,14,19,34,11,37,20,12,21,27,28,23,9,27,36,27,21,33,25,33,27,23],[11,70,13,24,17,22,28,36,15,44],[11,20,32,23,19,19,73,18,38,39,36,47,31],[22,23,15,17,14,14,10,17,32,3],[22,13,26,21,27,30,21,22,35,22,20,25,28,22,35,22,16,21,29,29,34,30,17,25,6,14,23,28,25,31,40,22,33,37,16,33,24,41,30,24,34,17],[6,12,8,8,12,10,17,9,20,18,7,8,6,7,5,11,15,50,14,9,13,31,6,10,22,12,14,9,11,12,24,11,22,22,28,12,40,22,13,17,13,11,5,26,17,11,9,14,20,23,19,9,6,7,23,13,11,11,17,12,8,12,11,10,13,20,7,35,36,5,24,20,28,23,10,12,20,72,13,19,16,8,18,12,13,17,7,18,52,17,16,13,5,23,11,13,12,9,9,5,8,28,22,35,44,48,43,13,31,7,10,10,9,8,18,19,2,29,176,7,8,9,4,8,5,6,5,6,8,8,3,18,3,3,21,26,9,8,24,13,10,7,12,15,21,10,20,14,9,6],[33,22,35,27,23,35,27,36,18,32,31,28,25,35,33,33,28,24,29,30,31,29,35,34,28,28,27,28,27,33,31],[18,26,22,16,20,12,29,17,18,20,10,14],[17,17,11,16,16,13,13,14],[31,22,26,6,30,13,25,22,21,34,16,6,22,32,9,14,14,7,25,6,17,25,18,23,12,21,13,29,24,33,9,20,24,17,10,22,38,22,8,31,29,25,28,28,25,13,15,22,26,11,23,15,12,17,13,12,21,14,21,22,11,12,19,12,25,24],[19,37,25,31,31,30,34,22,26,25,23,17,27,22,21,21,27,23,15,18,14,30,40,10,38,24,22,17,32,24,40,42,25,22,19,32,21,28,18,16,18,22,13,30,5,28,7,47,39,46,64,34],[22,22,66,22,22],[28,10,27,17,17,14,27,18,11,22,25,28,23,23,8,63,24,32,14,49,32,31,49,26,17,21,36,26,21,26,18,32,33,31,15,38,28,23,29,49,26,20,27,31,25,24,23,35],[21,49,30,37,31,28,28,27,27,21,45,13],[11,23,5,19,15,11,16,14,17,15,12,14,16,9],[20,32,21],[15,16,15,13,27,14,17,14,15],[21],[17,10,10,11],[16,13,12,13,15,16,20],[15,13,19],[17,20,19],[18,15,20],[15,23],[21,13,10,14,11,15,14,23,17,12,17,14,9,21],[14,17,18,6],[25,23,17,25,48,34,29,34,38,42,30,50,58,36,39,28,27,35,30,34,46,46,39,51,46,75,66,20],[45,28,35,41,43,56,37,38,50,52,33,44,37,72,47,20],[80,52,38,44,39,49,50,56,62,42,54,59,35,35,32,31,37,43,48,47,38,71,56,53],[51,25,36,54,47,71,53,59,41,42,57,50,38,31,27,33,26,40,42,31,25],[26,47,26,37,42,15,60,40,43,48,30,25,52,28,40,40,34,28,41,38,40,30,35,26,27,32,44,31],[32,29,31,25,21,23,25,39,32,21,36,21,14,23,33,27],[31,16,23,21,13,20,40,13,27,33,34,31,13,40,58,24],[24,17,18,18,21,18,16,24,15,18,33,21,13],[24,21,29,31,26,18],[23,22,21,32,33,24],[30,30,21,23],[29,23,25,18],[10,20,13,18,28],[12,17,18],[20,15,16,16,25,21],[18,26,17,22],[16,15,15],[25],[14,18,19,16,14,20,28,13,28,39,40,29,25],[27,26,18,17,20],[25,25,22,19,14],[21,22,18],[10,29,24,21,21],[13],[15],[25],[20,29,22,11,14,17,17,13,21,11,19,17,18,20,8,21,18,24,21,15,27,21]];

function versesInChapter(bookIdx, chapter) {
  return VERSE_COUNTS[bookIdx]?.[chapter - 1] ?? 0;
}

// ===== computus.ts port =====

function easterSunday(year) {
  const a = year % 19;
  const b = Math.floor(year / 100);
  const c = year % 100;
  const d = Math.floor(b / 4);
  const e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4);
  const k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const month = Math.floor((h + l - 7 * m + 114) / 31);
  const day = ((h + l - 7 * m + 114) % 31) + 1;
  return new Date(year, month - 1, day);
}

function palmSunday(year) {
  const easter = easterSunday(year);
  return new Date(easter.getFullYear(), easter.getMonth(), easter.getDate() - 7);
}

function toDayNumber(date) {
  return Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86400000);
}

function isHolyWeek(date) {
  const y = date.getFullYear();
  const d = toDayNumber(date);
  return d >= toDayNumber(palmSunday(y)) && d <= toDayNumber(easterSunday(y));
}

// ===== christmasReadings.ts port =====
// bookIdx values below match this file's own BOOK_CHAPTERS/VERSE_COUNTS
// order: 22=Isaiah, 32=Micah, 41=Luke, 39=Matthew, 42=John, 55=Titus, 18=Psalms.

const CHRISTMAS_READINGS = {
  18: { bookIdx: 22, chapter: 9, verseStart: 2, verseEnd: 7 },
  19: { bookIdx: 22, chapter: 7, verseStart: 10, verseEnd: 14 },
  20: { bookIdx: 32, chapter: 5, verseStart: 2, verseEnd: 5 },
  21: { bookIdx: 41, chapter: 1, verseStart: 26, verseEnd: 38 },
  22: { bookIdx: 41, chapter: 1, verseStart: 46, verseEnd: 56 },
  23: { bookIdx: 39, chapter: 1, verseStart: 18, verseEnd: 25 },
  24: { bookIdx: 41, chapter: 2, verseStart: 1, verseEnd: 7 },
  25: { bookIdx: 41, chapter: 2, verseStart: 8, verseEnd: 20 },
  26: { bookIdx: 39, chapter: 2, verseStart: 1, verseEnd: 12 },
  27: { bookIdx: 42, chapter: 1, verseStart: 1, verseEnd: 14 },
  28: { bookIdx: 41, chapter: 2, verseStart: 21, verseEnd: 40 },
  29: { bookIdx: 55, chapter: 2, verseStart: 11, verseEnd: 14 },
  30: { bookIdx: 55, chapter: 3, verseStart: 4, verseEnd: 7 },
  31: { bookIdx: 18, chapter: 90, verseStart: 1, verseEnd: 12 },
};

// ===== dailyPlan.ts port =====

const MATTHEW = 39, MARK = 40, LUKE = 41, JOHN = 42, PSALMS = 18;

const GOSPEL_ROTATION_BASE_YEAR = 2024;
const GOSPEL_ROTATION = [MARK, JOHN, MATTHEW, LUKE];

function gospelBookIdxForYear(year) {
  const offset = (((year - GOSPEL_ROTATION_BASE_YEAR) % 4) + 4) % 4;
  return GOSPEL_ROTATION[offset];
}

const HOLY_WEEK_CHAPTER_COUNT = { [MATTHEW]: 3, [MARK]: 3, [LUKE]: 3, [JOHN]: 4 };

// Same book order/grouping as the app's MAIN_QUEUE_BLOCKS, expressed
// as this file's own 0-indexed bookIdx values instead of BOOKS.findIndex.
// Genesis=0 Exodus=1 Leviticus=2 Numbers=3 Deuteronomy=4 Joshua=5 Judges=6
// Ruth=7 1Sam=8 2Sam=9 1Ki=10 2Ki=11 1Chr=12 2Chr=13 Ezra=14 Neh=15
// Esther=16 Job=17 Psalms=18 Prov=19 Eccl=20 Song=21 Isaiah=22 Jer=23
// Lam=24 Ezek=25 Dan=26 Hos=27 Joel=28 Amos=29 Obad=30 Jonah=31 Micah=32
// Nahum=33 Hab=34 Zeph=35 Hag=36 Zech=37 Mal=38 Matt=39 Mark=40 Luke=41
// John=42 Acts=43 Rom=44 1Cor=45 2Cor=46 Gal=47 Eph=48 Phil=49 Col=50
// 1Thess=51 2Thess=52 1Tim=53 2Tim=54 Titus=55 Phlm=56 Heb=57 James=58
// 1Pet=59 2Pet=60 1Jn=61 2Jn=62 3Jn=63 Jude=64 Rev=65
const MAIN_QUEUE_BLOCKS = [
  [0], [44, 55], [1], [49, 30, 56], [5, 6, 7], [45, 31], [8, 9], [47, 33],
  [10, 11], [46, 34], [22], [48, 35], [17], [50, 36, 38], [23, 24],
  [51, 52, 32], [3], [53, 54, 27], [25], [57, 28], [12, 13], [58, 29],
  [2], [59, 37], [26], [60, 61, 62, 63, 64], [4], [20, 21], [43],
  [19, 14, 15, 16], [65],
];
const MAIN_QUEUE = MAIN_QUEUE_BLOCKS.flat();

const TARGET_VERSES_PER_DAY_MAIN = 8;
const TARGET_VERSES_PER_DAY_PSALMS = 6;

function splitChapterIntoDays(bookIdx, chapter, dayCount) {
  const total = versesInChapter(bookIdx, chapter);
  const n = Math.max(1, dayCount);
  const base = Math.floor(total / n);
  const rem = total % n;
  const slots = [];
  let v = 1;
  for (let i = 0; i < n; i++) {
    const len = Math.max(1, base + (i < rem ? 1 : 0));
    const verseStart = v;
    const verseEnd = Math.min(v + len - 1, total);
    slots.push({ bookIdx, chapter, verseStart, verseEnd });
    v = verseEnd + 1;
  }
  return slots;
}

function allocateChapterDays(bookIdx, chapter, targetVersesPerDay) {
  const total = versesInChapter(bookIdx, chapter);
  const dayCount = Math.max(1, Math.ceil(total / targetVersesPerDay));
  return splitChapterIntoDays(bookIdx, chapter, dayCount);
}

function stretchToFit(bookIdx, chapters, totalDays) {
  if (chapters.length === 0 || totalDays <= 0) return [];
  const days = Math.max(totalDays, chapters.length);
  const verseCounts = chapters.map((c) => versesInChapter(bookIdx, c));
  const totalVerses = verseCounts.reduce((s, v) => s + v, 0);
  const raw = verseCounts.map((v) => (v / totalVerses) * days);
  const dayCounts = raw.map((r) => Math.max(1, Math.floor(r)));
  let remaining = days - dayCounts.reduce((s, v) => s + v, 0);
  const order = raw
    .map((r, i) => ({ i, frac: r - Math.floor(r) }))
    .sort((a, b) => b.frac - a.frac);
  for (let k = 0; k < order.length && remaining > 0; k++, remaining--) {
    dayCounts[order[k].i]++;
  }
  const slots = [];
  chapters.forEach((chapter, i) => {
    slots.push(...splitChapterIntoDays(bookIdx, chapter, dayCounts[i]));
  });
  return slots;
}

function buildSchedule(bookIndices, targetVersesPerDay) {
  const schedule = [];
  for (const bookIdx of bookIndices) {
    const chapterCount = BOOK_CHAPTERS[bookIdx];
    for (let chapter = 1; chapter <= chapterCount; chapter++) {
      schedule.push(...allocateChapterDays(bookIdx, chapter, targetVersesPerDay));
    }
  }
  return schedule;
}

const MAIN_SCHEDULE = buildSchedule(MAIN_QUEUE, TARGET_VERSES_PER_DAY_MAIN);
const PSALMS_SCHEDULE = buildSchedule([PSALMS], TARGET_VERSES_PER_DAY_PSALMS);

const PLAN_EPOCH = new Date(2024, 0, 1);

function classifyDay(date) {
  const month = date.getMonth();
  const day = date.getDate();
  if (month === 11 && day >= 18) return 'christmas';
  if (isHolyWeek(date)) return 'gospel';
  if (date.getDay() === 0) return 'psalms';
  const easter = easterSunday(date.getFullYear());
  if (toDayNumber(date) <= toDayNumber(easter)) return 'gospel';
  return 'main';
}

function typeIndexForDate(date, type) {
  let count = 0;
  const cursor = new Date(PLAN_EPOCH.getFullYear(), PLAN_EPOCH.getMonth(), PLAN_EPOCH.getDate());
  const targetDayNum = toDayNumber(date);
  while (toDayNumber(cursor) < targetDayNum) {
    if (classifyDay(cursor) === type) count++;
    cursor.setDate(cursor.getDate() + 1);
  }
  return count;
}

function slotToReading(type, slot) {
  return { type, bookIdx: slot.bookIdx, chapter: slot.chapter, verseStart: slot.verseStart, verseEnd: slot.verseEnd };
}

function resolveGospelReading(date) {
  const year = date.getFullYear();
  const bookIdx = gospelBookIdxForYear(year);
  const totalChapters = BOOK_CHAPTERS[bookIdx];
  const holyWeekChapters = HOLY_WEEK_CHAPTER_COUNT[bookIdx];

  if (isHolyWeek(date)) {
    const start = palmSunday(year);
    const chapters = Array.from({ length: holyWeekChapters }, (_, i) => totalChapters - holyWeekChapters + 1 + i);
    const windowDays = toDayNumber(easterSunday(year)) - toDayNumber(start) + 1;
    const slots = stretchToFit(bookIdx, chapters, windowDays);
    const offset = toDayNumber(date) - toDayNumber(start);
    const slot = slots[Math.min(offset, slots.length - 1)];
    return slotToReading('gospel', slot);
  }

  const jan1 = new Date(year, 0, 1);
  const palm = palmSunday(year);
  const chapters = Array.from({ length: totalChapters - holyWeekChapters }, (_, i) => i + 1);
  const windowDays = toDayNumber(palm) - toDayNumber(jan1);
  const slots = stretchToFit(bookIdx, chapters, windowDays);
  const offset = toDayNumber(date) - toDayNumber(jan1);
  const slot = slots[Math.min(offset, slots.length - 1)];
  return slotToReading('gospel', slot);
}

/** Same algorithm as the app's getReadingForDate, returning
 *  { type, bookIdx, chapter, verseStart, verseEnd } (bookIdx 0-indexed —
 *  add 1 for the worker's 1-indexed book-number endpoints). */
export function getReadingForDate(date) {
  const type = classifyDay(date);

  if (type === 'christmas') {
    return slotToReading('christmas', CHRISTMAS_READINGS[date.getDate()]);
  }
  if (type === 'gospel') {
    return resolveGospelReading(date);
  }
  const schedule = type === 'psalms' ? PSALMS_SCHEDULE : MAIN_SCHEDULE;
  const index = typeIndexForDate(date, type) % schedule.length;
  return slotToReading(type, schedule[index]);
}
